name: 'Terraform Plan'

on:
  push:
    branches:
      - master
  pull_request:
env:
  TF_VAR_public_key: secrets.TF_VAR_PUBLIC_KEY
  AWS_ACCESS_KEY_ID: secrets.AWS_ACCESS_KEY_USER
  AWS_SECRET_ACCESS_KEY: secrets.AWS_ACCESS_KEY_SECRET
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:        
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

    #  - name: Terraform Apply
    #    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    #    run: terraform apply -auto-approve
